name: Test Build Website

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/deploy-website.yml'
      - 'website/**'
      - 'react-native-pytorch-core/src/**'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/deploy-website.yml'
      - 'website/**'
      - 'react-native-pytorch-core/src/**'

jobs:
  checks:
    name: Test Build 🧪
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: website/yarn.lock
      - name: Install dependencies 🧶
        run: yarn install --frozen-lockfile
      - name: Test build website 🧪
        run: yarn build
